language: php
php:
  - '5.3'
before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit
  - phpunit --configuration phpunit.xml