language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  
install:
  - composer install

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash)